apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-a
  namespace: argocd
  annotations:
    # argocd-image-updater.argoproj.io/image-list: service-a=deepenc/service-a:~0.1
    argocd-image-updater.argoproj.io/service-a.update-strategy: semver
    argocd-image-updater.argoproj.io/image-list: service-a=deepenc/service-a
    # argocd-image-updater.argoproj.io/service-a.update-strategy: name
    # argocd-image-updater.argoproj.io/service-a.allow-tags: regexp:^(stag|prod)-[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/git-branch: 0.1-develop
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-commit-message: "chore: update image tags [skip ci]"
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    # Below annonations are for clear Git commit history and needs verified commits under a specific user/email
    # These are optional, when not defined, argocd uses its default ones
    # argocd-image-updater.argoproj.io/git-commit-user: Argo Image Updater
    # argocd-image-updater.argoproj.io/git-commit-email: sunilojha525@gmail.com
spec:
  project: default
  source:
    repoURL: "https://github.com/sapkotapratik007/argocd-microservice-demo"
    targetRevision: "0.1-develop"
    path: service-a/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=false
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
